all: task3_1_general task3_1_subor

task3_1_general: task3_1_general.c
	gcc task3_1_general.c -o task3_1_general

task3_1_subor: task3_1_subor.c
	gcc task3_1_subor.c -o task3_1_subor

clean:
	rm -f *.o task3_1_general task3_1_subor